# Generated by Django 4.1.7 on 2023-05-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='profile_pic',
            field=models.BinaryField(blank=True),
        ),
    ]
