# Generated by Django 4.1.7 on 2023-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='css',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='js',
            field=models.TextField(blank=True),
        ),
    ]
